config/routes.rb
Spree::Core::Engine.routes.draw do

  get "additional_order_detail_tabs" => 'AdditionalOrderDetails#main', as: :additional_order_detail_tabs

  scope '/api' do
    resources :additional_order_details
  end


  resources :additional_order_details

  namespace :admin do
    resources :additional_order_detail_descriptors

    resources :orders do
      get :additional_order_detail, on: :member
    end
    resources :products do
      resources :additional_order_detail_descriptors do
        member do
          post :select
          get :remove
        end

        collection do
          get :available
          get :selected
        end

        get :select

      end
    end

    resources :option_values do
      resources :additional_order_detail_descriptors do
        member do
          post :select
          get :remove
        end

        collection do
          get :available
          get :selected
        end

        get :select

      end
    end

  end
end

# need something like
# match '*path', to: 'AdditionalOrderDetail#main'
# at the very end of our routes due to pushState (see very end of http://railscasts.com/episodes/325-backbone-on-rails-part-2)

app/models/spree/additional_order_detail_descriptor.rb
class Spree::AdditionalOrderDetailDescriptor < ActiveRecord::Base
  attr_accessible :describable_id, :describable_type, :model_name, :step_name, :position

  belongs_to :describable, polymorphic: true
end

app/controllers/spree/admin/additional_order_detail_descriptors_controller.rb
module Spree
  class Admin::AdditionalOrderDetailDescriptorsController < Admin::ResourceController
    before_filter :load_object, :only => [:selected, :available, :remove]

    def available
      set_available_additional_order_detail_descriptors
      render :layout => false
    end

    def selected
      @additional_order_detail_descriptors = @object.additional_order_detail_descriptors
    end

    def remove
      @object.additional_order_detail_descriptors.delete(@additional_order_detail_descriptor)
      @object.save
      flash.notice = I18n.t("notice_messages.additional_order_detail_descriptor_removed")
      redirect_to appropriate_route
    end

    # AJAX method for selecting an existing option type and associating with the current object
    def select
      @object = find_appropriate_object
      model_name = params[:additional_order_detail_model_name]
      @object.additional_order_detail_descriptors.create(step_name: model_name.split("::").last.underscore.to_sym, model_name: model_name)

      @additional_order_detail_descriptors = @object.additional_order_detail_descriptors
      set_available_additional_order_detail_descriptors
    end

    protected

    private

    def appropriate_route
      return selected_admin_product_additional_order_detail_descriptors_url(@object) if @object.kind_of?(Spree::Product)
      return selected_admin_option_value_additional_order_detail_descriptors_url(@object) if @object.kind_of?(Spree::OptionValue)
    end

    def find_appropriate_object
      return Product.find_by_param!(params[:product_id]) if params[:product_id]
      return OptionValue.find(params[:option_value_id]) if params[:option_value_id]
    end

    def load_object
      @object = Product.find_by_param!(params[:product_id]) if params[:product_id]
      @object = OptionValue.find(params[:option_value_id]) if params[:option_value_id]
    end

    def set_available_additional_order_detail_descriptors
      @available_additional_order_detail_models = Rails.application.config.spree.additional_order_detail_models.dup

      selected_additional_order_detail_models = []
      @object.additional_order_detail_descriptors.each do |d|
        selected_additional_order_detail_models << d
      end

      @available_additional_order_detail_models.delete_if {|m| selected_additional_order_detail_models.map(&:model_name).include? m.to_s}
    end
  end
end

app/views/spree/admin/additional_order_detail_descriptors/_available.html.erb
<h4><%= t("add_additional_order_detail_descriptors") %></h4>
<table class="index">
  <tr>
    <th><%= t("name") %></th>
    <th>&nbsp;</th>
  </tr>
  <% @available_additional_order_detail_models.each do |name| %>
  <tr>
    <td><%=name %></td>
    <% url_hash = {:controller => "admin/additional_order_detail_descriptors",
                                    :id => name.to_s,
                                    :action => "select",
                                    :additional_order_detail_model_name =>  name.to_s}

    if @object.kind_of?(Spree::Product)
      url_hash[:product_id] = @object.permalink
    elsif @object.kind_of?(Spree::OptionValue)
      url_hash[:option_value_id] = @object.id
    end
    %>

    <td class="actions"><%= link_to icon('add') + ' ' + t("select"),
                            url_for(url_hash),
                           :remote => true, :class => 'iconlink' %>
    </td>
  </tr>
  <% end %>
  <% if @available_additional_order_detail_models.empty? %>
  <tr>
    <td colspan="3"><%= t('none_available') %></td>
  </tr>
  <% end %>
</table>

app/views/spree/admin/additional_order_detail_descriptors/_selected.html.erb
<table class="index">
  <tr>
    <th><%= t("step_name") %></th>
    <th><%= t("model_name") %></th>
    <th>&nbsp;</th>
  </tr>
  <% @additional_order_detail_descriptors.each do |additional_order_detail_descriptor| %>
    <tr>
      <td><%= additional_order_detail_descriptor.step_name %></td>
      <td><%= additional_order_detail_descriptor.model_name %></td>
      <td class="actions">
        <%= link_to_with_icon 'delete',  t("remove"), additional_order_detail_remove_route_for(@object, additional_order_detail_descriptor) %>
      </td>
    </tr>
  <% end %>
  <% if @additional_order_detail_descriptors.empty? %>
   <tr><td colspan="3"><%= t(:none) %></td></tr>
  <% end %>
</table>

<div id="additional-order-detail-descriptors"></div>
  <span id="new_descriptor_link_span">
    <%= link_to icon('add') + ' ' + t("add_additional_order_detail_descriptor"), additional_order_detail_available_route_for(@object), :remote => :true, :class => 'iconlink', :id => "new_descriptor_link" %>
  </span>

app/views/spree/admin/additional_order_detail_descriptors/available.js.erb
$("#additional-order-detail-descriptors").html("<%= raw escape_javascript(render('available')) %>");
$("#new_descriptor_link_span").hide();

app/views/spree/admin/additional_order_detail_descriptors/index.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<h1><%= t("additional_order_detail_descriptors") %></h1>

<div id="new_additional_order_detail_descriptor"></div>

<table class="index sortable" id='listing_additional_order_detail_descriptors'>
  <tr>
    <th><%= t("step_name") %></th>
    <th><%= t("model_name") %></th>
    <th><%= t("describable") %></th>
    <th></th>
  </tr>
  <% @additional_order_detail_descriptors.each do |additional_order_detail_descriptor| %>
    <tr id="<%= dom_id additional_order_detail_descriptor %>">
      <td><span class="handle"></span> <%= additional_order_detail_descriptor.step_name %></td>
      <td class='presentation'><%= additional_order_detail_descriptor.model_name %></td>
      <td class='description'><%= additional_order_detail_descriptor.describable.try(:name) %></td>
      <td class="actions">
        <%= link_to_delete(additional_order_detail_descriptor) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/spree/admin/additional_order_detail_descriptors/new.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render 'spree/shared/error_messages', :target => @additional_order_detail_descriptor%>

<%= form_for(@additional_order_detail_descriptor, :url => admin_additional_order_detail_descriptors_url) do |f| %>
  <fieldset>
    <legend><%= t("new_additional_order_detail_descriptor") %></legend>
    <%= render :partial => "form", :locals => { :f => f } %>
<!--     < %= render :partial => 'spree/admin/shared/new_resource_links' % >

put this back in once r_c is removed
-->


<p class="form-buttons">
  <%= button t("actions.create") %>
  <%= t("or") %> <%= link_to t("actions.cancel"), admin_additional_order_detail_descriptors_url %>
</p>


  </fieldset>
<% end %>

app/views/spree/admin/additional_order_detail_descriptors/select.js.erb
$("#selected-customization-types").html("<%= raw escape_javascript(render 'selected') %>");
$("#customization-types").html("");
$("#new_ct_link").show();

app/views/spree/admin/additional_order_detail_descriptors/selected.html.erb
<% if @object.kind_of?(Spree::Product) %>
<% @product = @object %>
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => I18n.t('additional_order_detail_descriptors')} %>
<% elsif @object.kind_of?(Spree::OptionValue) %>
   <h1><%= t("additional_order_detail_descriptors") %> for <%= @object.presentation %> </h1>
<% end %>
<div id="selected-customization-types">
  <%= render 'selected' %>
</div>